version: 2
jobs:
  android:
    working_directory: ~/repo
    docker:
      - image: reactnativecommunity/react-native-android
    steps:
      - checkout
      - run: yarn install
      - run: cd android && chmod +x gradlew && ./gradlew assembleRelease
      - store_artifacts:
          path: ./android/app/build/outputs
          destination: apk-file

workflows:
  version: 2
  build_and_test:
    jobs:
      - android
